[package]
name = "tigris-caffeine"
version = "0.1.0"
edition = "2021"

[dependencies]
caffeine-cli = "1.0.1"
tigris-core = { path = "/home/lighttigerxiv/dev/whiskers-apps/pc/tigris-core", features = [
    "extension",
] }
